export type { default as Game } from './Game'
export type { default as Genre } from './Genre'
export type { default as Platform } from './Platform'
export type { default as Publisher } from './Publisher'
export type { default as ScreenShot } from './ScreenShot'
export type { default as Trailer } from './Trailer'
